version: '3.8'

services:
  # Banco PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: erp-postgres
    environment:
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: erp_password
      POSTGRES_DB: erp_imobiliario
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # Redis para cache e sessões
  redis:
    image: redis:7-alpine
    container_name: erp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: erp-backend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=postgresql://erp_user:erp_password@postgres:5432/erp_imobiliario?schema=public
      - JWT_SECRET=super-secret-jwt-key-production
      - JWT_REFRESH_SECRET=super-secret-refresh-key-production
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGIN=http://localhost:5173
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ../uploads:/app/uploads
      - ../logs:/app/logs
    restart: unless-stopped

  # pgAdmin para administração do banco
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: erp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@erp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: erp-network